[project]
name = "device-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cristian Pereira", email = "pereiracamilo51@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic[email]>=2.13.5",
    "uvicorn>=0.52.4",
]

[project.scripts]
device-systems = "device_systems:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
